export const MESSAGE_TYPES = {
  RESPONSE: 'RESPONSE',
  REQUEST: 'REQUEST',
  REQUEST_CONTEXT: 'REQUEST_CONTEXT',
  LOG: 'LOG',
} as const;

export const REQUEST_ACTIONS = {
  SHOW_CALLBAR: 'SHOW_CALLBAR',
  HIDE_CALLBAR: 'HIDE_CALLBAR',
  CREATE: 'CREATE',
  DELETE: 'DELETE',
  UPDATE: 'UPDATE',
  QUERY: 'QUERY',
  SHOW_BADGE: 'SHOW_BADGE',
  HIDE_BADGE: 'HIDE_BADGE',
  GET_SETTINGS: 'GET_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  UPLOAD_FILE: 'UPLOAD_FILE',
  UPLOAD_RECORD_FILE: 'UPLOAD_RECORD_FILE',
  DELETE_FILE: 'DELETE_FILE',
  GET_FILES: 'GET_FILES',
  GET_RECORD_FILES: 'GET_RECORD_FILES',
  GET_FILE: 'GET_FILE',
} as const;

export const TIMEOUT_DURATION = 60000; // one minute;
